[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
; Keep debug symbols and a debug-friendly optimization level for GDB stepping
build_unflags = -Os
build_flags = -Og -g3
lib_deps =
    throwtheswitch/Unity@^2.5.2

[env:native]
platform = native
test_ignore = no_main
; Build the desktop test runner as a normal host program
build_src_flags = -DUNIT_TEST_DESKTOP
extra_scripts = pre:test/desktop_pre.py
